version check

diff --git a/.github/workflows/e2e-test-no-domain.yaml b/.github/workflows/e2e-test-no-domain.yaml
--- a/.github/workflows/e2e-test-no-domain.yaml
+++ b/.github/workflows/e2e-test-no-domain.yaml
@@ -37,39 +37,45 @@ jobs:
         uses: actions/setup-go@v2.1.4
         with:
           go-version: 1.17
-
-      - name: Setup dependencies
-        id: setup-dependencies
-        working-directory: test/
+      
+      - name: Print CLI version
+        id: cli-version
         run: |
-          go get -v -t -d ./... && go mod tidy
-          echo ::set-output name=exit_code::$?
+          kubectl version
+          aws --version
 
-      - name: Create test output directory
-        run: mkdir test/e2etest/artifacts
+      # - name: Setup dependencies
+      #   id: setup-dependencies
+      #   working-directory: test/
+      #   run: |
+      #     go get -v -t -d ./... && go mod tidy
+      #     echo ::set-output name=exit_code::$?
 
-      - name: Add private SSH key for Bitbucket tests
-        uses: shimataro/ssh-key-action@v2
-        with:
-          key: ${{ secrets.BITBUCKET_E2E_TEST_PRIV_SSH_KEY }}
-          name: bitbucket-e2e # optional
-          known_hosts: dummy-entry
-          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
+      # - name: Create test output directory
+      #   run: mkdir test/e2etest/artifacts
 
-      - name: Add public SSH key for Bitbucket tests
-        run: |
-          echo ${{ secrets.BITBUCKET_E2E_TEST_PUB_SSH_KEY }} > /home/runner/.ssh/bitbucket-e2e.pub
+      # - name: Add private SSH key for Bitbucket tests
+      #   uses: shimataro/ssh-key-action@v2
+      #   with:
+      #     key: ${{ secrets.BITBUCKET_E2E_TEST_PRIV_SSH_KEY }}
+      #     name: bitbucket-e2e # optional
+      #     known_hosts: dummy-entry
+      #     if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
 
-      - name: E2E Testing with no domain
-        id: e2e-test
-        working-directory: test/
-        run: |
-          set -o pipefail
-          go test ./e2etest -v -timeout 85m -run Installer | tee ./e2etest/artifacts/e2etest.log
+      # - name: Add public SSH key for Bitbucket tests
+      #   run: |
+      #     echo ${{ secrets.BITBUCKET_E2E_TEST_PUB_SSH_KEY }} > /home/runner/.ssh/bitbucket-e2e.pub
 
-      - name: Upload test log files
-        if: always()
-        uses: actions/upload-artifact@v2
-        with:
-          name: e2e-test-artifacts
-          path: test/e2etest/artifacts/
+      # - name: E2E Testing with no domain
+      #   id: e2e-test
+      #   working-directory: test/
+      #   run: |
+      #     set -o pipefail
+      #     go test ./e2etest -v -timeout 85m -run Installer | tee ./e2etest/artifacts/e2etest.log
+
+      # - name: Upload test log files
+      #   if: always()
+      #   uses: actions/upload-artifact@v2
+      #   with:
+      #     name: e2e-test-artifacts
+      #     path: test/e2etest/artifacts/
